### PR TITLE
Share files using a content provider

### LINKED ISSUE #43: Stop using file:// uri for sharing screenshot
When you target N sharing a `file://` uri will cause a `FileUriExposedException` [(source)](https://developer.android.com/preview/behavior-changes.html#permfilesys). There is also a StrictMode check for this since API 18.

### PR DESCRIPTION
**Pull request by mattprecious**
Closes #43

### CODE REVIEW

File: telescope/src/main/java/com/mattprecious/telescope/support/FileProvider.java [hunk 1]
```diff
@@ -0,0 +1,768 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/*
+ * A copy of support-v4's FileProvider that supports a new <external-app-path/> tag which uses
+ * Context.getExternalFilesDir(null) as its root.
```
Comment (JakeWharton) [inline telescope/src/main/java/com/mattprecious/telescope/support/FileProvider.java]: Link to b/ issue so you can know when to delete this.
